version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - amandel
  labels:
  - skip-changelog

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
